### ISSUE TITLE
Feat: User type Outstanding tasks

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/open-api#104]
- [x] remove or improve deleteGDPRUser
- [x] agree if tests should have uncaught errors

From https://github.com/freeCodeCamp/open-api/pull/55#issuecomment-386158708

**Comment by Bouncey** [comment]
So, expanding on my comments re: uncaught errors, maybe my explanation was way off. These errors that are flagged to the console are errors we will find during implementation and should not reach any client code. If they are triggered out in the wild, we send a generic `Something went wrong` message to the client whilst logging the actual error for ourselves to aid debugging.

As always, I am open to other ways of doing things. You guys, hands down, have more experience than me. This is the first 'real' back end I have had a hand in, so my learning curve is still steep. 

I am not precious with my code, if it can be better please tell me or raise a PR. Feedback is always welcome. :+1:

**Comment by Bouncey** [comment]
GDPR endpoints (are they still endpoints in graphql?) should be improved/implemented as a priority.

**Comment by ojongerius** [comment]
deleteGDPRUser was removed and logging decision explained. Thanks @Bouncey
