### ISSUE TITLE
chore: planning and discussions.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/open-api#11]
Close and move issues from https://github.com/freeCodeCamp/freeCodeCamp/projects/5 to this tracker.

We should still be using the project board above, while reporting and discussing the threads here.

**Comment by ojongerius** [comment]
@raisedadead I've raised https://github.com/freeCodeCamp/freeCodeCamp/issues/16918 in regards to this issue. I suggest we create a new project, but on an organisational instead of repository level. In that way we are able to link issues and PRs from multiple repositories. Shall we discuss there?

**Comment by ojongerius** [comment]
Right so this task can be started as @raisedadead mentioned we'll use the board there and use issues in this project, at least until Github fixes their organisational boards.

**Comment by ojongerius** [comment]
@raisedadead I can't edit https://github.com/freeCodeCamp/freeCodeCamp/projects/5 it would probably help to make me a member of the freeCodeCamp organisation, unless their is a lot of red tape to cut through.

**Comment by QuincyLarson** [comment]
@ojongerius Thanks for your patience. OK - I think you now have write permission on every freeCodeCamp repo. Please confirm whether you're able to update the project board now.

**Comment by ojongerius** [comment]
@QuincyLarson thank you! Can confirm I am able to update the board.

**Comment by ojongerius** [comment]
Just tried link some https://github.com/freeCodeCamp/open-api issues on https://github.com/freeCodeCamp/freeCodeCamp/projects/5 but it seems this is scoped to the https://github.com/freeCodeCamp/freeCodeCamp board 😠 

@raisedadead what did you have in mind, using cards and linking to issues here? How about we just use a project board here?

**Comment by raisedadead** [comment]
> How about we just use a project board here?

Yes, lets do that. It would be easier to sort things that way. Sorry about the frustrations with project board. 😓 

Would you like to move them over? I can take care of it as well if you prefer.

**Comment by ojongerius** [comment]
No problem at all @raisedadead. I've added all current issues to the board. I'd love it if you could take care of the issues on https://github.com/freeCodeCamp/freeCodeCamp/projects/5 as you have a lot more context about these issues.

I'll spike an GraphQL endpoint, and it would be nice if we could have setup a meeting next week to go through the current strategy and more high level things like deployment (https://github.com/freeCodeCamp/open-api/issues/26) , authentication (https://github.com/freeCodeCamp/open-api/issues/23) general security (https://github.com/freeCodeCamp/open-api/issues/25) and some of the open issues on the old board at https://github.com/freeCodeCamp/freeCodeCamp/projects/5

**Comment by raisedadead** [comment]
@ojongerius sure, I will do that when I can. I have gone ahead and done some house keeping on the repo, sorry made direct commits, but I found that to be fine since we are on a clean slate.

I removed all of the old code, (psst.. we have a archive branch for posterity of the earlier work, which is locked for the same reason).

But, from now on here is what we should follow:

1. Make PR from our forks. I promise I'll follow this too.
2. Have Git flow based branches.
3. Use conventional commits (am also working on the commitlint thing)

I am up for that meeting, feel free to send an invite. I am guessing the same time as last should be fine?

**Comment by QuincyLarson** [comment]
@ojongerius It sounds like you all have everything you need here, but I just wanted to say I'm always available if I can be of any help. 

I'm creating a few new projects on the Open API repo with user stories, which you and @raisedadead can interpret and turn into GitHub issues.

**Comment by ojongerius** [comment]
@raisedadead great, I've shot you an invite, same time, April 3.

@QuincyLarson indeed, all set! Does @raisedadead have context about the events project?

**Comment by raisedadead** [comment]
Yes, I do.. we will send you one more meeting invite to discuss this more specifically

**Comment by ojongerius** [comment]
Great, case closed as far as I am concerned.

**Comment by ojongerius** [comment]
@QuincyLarson / @raisedadead just a heads up that public org projects board are now supported!

> Just a quick update to let you know that it is now possible to create public organization wide project boards:
> https://blog.github.com/2018-03-28-improved-organization-project-permissions/#public-organization-projects
> I hope this helpful. If you have any questions or suggestions for improvements, please do let us know!

**Comment by QuincyLarson** [comment]
@ojongerius @raisedadead Awesome! I just re-opened our project board and set it to public! https://github.com/orgs/freeCodeCamp/projects/1

Anyone with write access to any of freeCodeCamp repos can now interact with it, and everyone can view it.

Let's use this as the central place for coordinating work on GraphQL APIs for our various projects. Would one of you like to populate it with the outstanding issues?

**Comment by ojongerius** [comment]
Done!
