### ISSUE TITLE
Update License files

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#12]
The current license is MIT ( https://github.com/freeCodeCamp/open-api/blob/staging/LICENSE ) and mentions "feathers", so I'm guessing it's a copy.
freeCodeCamp uses BSD 3-Clause (https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/LICENSE.md) for the code. 

There is another license file https://github.com/freeCodeCamp/open-api/blob/staging/LICENSE.md that seems to pertain to the the dataset, and refers to http://opendatacommons.org/licenses/odbl/1.0/

@raisedadead do you know what to do here? Are there any guidelines or strong opinions here?

**Comment by raisedadead** [comment]
All software code at freeCodeCamp is to be BSD 3-Clause. All data sets, are to be Licensed CC-BY-SA-4.0

The repo's root should have a BSD 3-Clause. Sub directory for a data set can have an additional CC-BY-SA-4.0 if applicable.

The readme should be reflecting this. An example would be the way its done on the main repo.

**Comment by raisedadead** [comment]
Task remaining : update readme
