### ISSUE TITLE
Modify the issue templates to suite Open-API

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/open-api#121]

**Comment by raisedadead** [comment]
Well actually the image link needs to be updated to `https://raw.githubusercontent.com/freeCodeCamp/open-api/staging/.github/ISSUE_TEMPLATE/share_playground.png`

**Comment by raisedadead** [comment]
Doesn't seem to work without that.

**Comment by ojongerius** [comment]
Nice catch @raisedadead
