### ISSUE TITLE
Querying non existent user returns generic error

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#127]
Querying for a non existing user will return "Something went wrong, please check and try again" however the logs show the Mongo returns "No user found for ..".

```sh
{ Error: No user found for otto@0tt0.net
    at getUserPromise (/Users/ojongerius/repos/fcc-open-api/.webpack/service/src/webpack:/src/dataLayer/mongo/user.js:28:14)
    at <anonymous>
  originalMessage: 'No user found for otto@0tt0.net',
  message: 'Error in resolver Query.getUser\nNo user found for otto@0tt0.net' }
Error: No user found for otto@0tt0.net
    at getUserPromise (/Users/ojongerius/repos/fcc-open-api/.webpack/service/src/webpack:/src/dataLayer/mongo/user.js:28:14)
    at <anonymous>
Error: Something went wrong, please check and try again
    at promise.catch.err (/Users/ojongerius/repos/fcc-open-api/.webpack/service/src/webpack:/src/utils/asyncErrorHandler.js:7:11)
    at <anonymous>
Serverless: [200] {"statusCode":200,"headers":{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":true},"body":"{\"data\":{\"getUser\":null},\"errors\":[{\"message\":\"Something went wrong, please check and try again\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"getUser\"]}]}"}
```

DoD:
- [x] We return the correct error
- [x] Test snapshot has been updated

**Comment by ojongerius** [comment]
Interesting, looking at the testing snapshot so this was expected behaviour:

```js
exports[`getUser should return null if no user has been found: no user error 1`] = `
Array [
  [GraphQLError: Something went wrong, please check and try again],
]
`;
```

However, nothing went wrong the user is not there. Retrying until the user has been created could take a lot of faith and time.

**Comment by ojongerius** [comment]
@Bouncey looks like you are overwriting the error message in `asyncErrorHandler`. What's the thought behind this?

**Comment by Bouncey** [comment]
Nice "catch".

I think my top level asyncErrorHandler either needs more work to just re-throw exceptions we have thrown ourselves, or removed completely.

**Comment by ojongerius** [comment]
Well played 😄 I'm happy to let it re-throw for now, and we can refactor later. I do see a use for masking internal errors with a default one, but informational errors we should bubble up. 

Writing this, it could be to our benefit to include unique IDs with those generic errors so we could find out which GW request and Lambda invocation a support issue would be about.

**Comment by ojongerius** [comment]
Found the root cause, and I got what I wanted.

We agree we can make things even better but this will do for now.
