### ISSUE TITLE
Create contributing file

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#13]
Too early to do now, but let's not forget to create a guide when this project is in a shape where it's ready for other contributors.

- [x] Add contributing guide on lines of the main repo, but minimal.
- [x] Add contacts for general queries. 
- [ ] ~~Add policy to report security issues.~~ have raised #146
- [x] Add instructions on creating a PR (for ex: PR must come from forks, etc.)

**Comment by raisedadead** [comment]
This and all GitHub related templates like ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE should go in `.github`.
