### ISSUE TITLE
Create CNAME for lambda deployments

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#140]
Stage is currently deployed to https://0pmplj77kg.execute-api.us-east-1.amazonaws.com/stage/api  and it would be nice to have something that is a little easier to remember.

@raisedadead we chatted about this, could you please create a CNAME, say either api-stage.freecodecamp.org or api.staging.freecodecamp.org and make it resolve to 0pmplj77kg.execute-api.us-east-1.amazonaws.com?

I can imagine that in the future we'd like to spin new versions up to a new stack and url, and control redirection to the new stack using DNS. For that I guess we'd delegate at least a subdomain to route53. However that is completely out of scope for this issue.

**Comment by raisedadead** [comment]
I think its best to keep it as `staging.api.freecodecamp.org`, and later on we can have `api.freecodecamp.org`, etc.

I would imagine in future if we do use a DNS automation that would be neat, for deploy-priview like URLs

**Comment by ojongerius** [comment]
However, using `staging.freecodecamp.org` would make all staging urls share the same namespace, which feels more tidy.

The other upside of using `staging.freecodecamp.org` would be that we, in the future, could delegate it to route53 and manipulate it programatically.

**Comment by raisedadead** [comment]
Yeah, you are right. However, I feel having a `api` in there is less ambiguous, and separates off the convention from web apps and pure APIs?

**Comment by Bouncey** [comment]
So, what are we CNAMEing to the staging lamda?

**Comment by raisedadead** [comment]
`api-stage.freecodecamp.org` => `0pmplj77kg.execute-api.us-east-1.amazonaws.com`
`api.freecodecamp.org` => `<some value when we have it>.execute-api.us-east-1.amazonaws.com`

**Comment by Bouncey** [comment]
`api-stage` is set

**Comment by ojongerius** [comment]
```bash
▶ git api-stage.freecodecamp.org
git: 'api-stage.freecodecamp.org' is not a git command. See 'git --help'.

~/repos/fcc-open-api  staging ✔                                                          19h55m ◒  ⍉
```

Ehm..

```bash
▶ dig api-stage.freecodecamp.org

; <<>> DiG 9.10.6 <<>> api-stage.freecodecamp.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39101
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;api-stage.freecodecamp.org.	IN	A

;; ANSWER SECTION:
api-stage.freecodecamp.org. 299	IN	CNAME	0pmplj77kg.execute-api.us-east-1.amazonaws.com.
0pmplj77kg.execute-api.us-east-1.amazonaws.com.	59 IN A	54.230.135.127
0pmplj77kg.execute-api.us-east-1.amazonaws.com.	59 IN A	54.230.135.118
0pmplj77kg.execute-api.us-east-1.amazonaws.com.	59 IN A	54.230.135.129
0pmplj77kg.execute-api.us-east-1.amazonaws.com.	59 IN A	54.230.135.231

;; Query time: 280 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu May 10 10:18:21 NZST 2018
;; MSG SIZE  rcvd: 179
```

🙇 thank you!
