### ISSUE TITLE
Document how to report security issues

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#146]
If people find serious vulnerabilities we'd like to know about it via a private channel, not an issue on GH.

We could consider https://securitytxt.org, but a simpler way would be to add a security contact in the issue templates. @QuincyLarson how do handle security issues at the moment? Is security@freecodecamp.org an email address?

**Comment by raisedadead** [comment]
Currently, we do not have a very clear way of reporting such issues. You can add team+security@freecodecamp.org as a email address.

**Comment by raisedadead** [comment]
I am considering Keybase for PGP encrypted emails for reporting as well. Stay tuned.

**Comment by imcodingideas** [comment]
Most larger companies have a `/whitehat` page with some instructions on how to report and a list of people who have found bugs.

May I suggest a landing page similar to:

https://www.facebook.com/whitehat 
https://www.google.com/about/appsecurity/reward-program/

Clearly an open source program can't afford paid bug boundaries but we could have some list?

**Comment by ojongerius** [comment]
I've raised an issue for this at https://github.com/freeCodeCamp/freeCodeCamp/issues/17154 as we won't have a landingpage for this project. 

We can however, add a link to that landing page in our CONTRIBUTING doc and issues templates.

**Comment by ojongerius** [comment]
Calling this closed. https://github.com/freeCodeCamp/freeCodeCamp/issues/17154 should cover having a proper page and https://github.com/freeCodeCamp/open-api/pull/155 added a security contact to the issue template.
