### ISSUE TITLE
Can't createUser with the header generated by `yarn generate-auth-header`

### ISSUE THREAD

**Issue by user512** [FreeCodeCamp/open-api#152]
#### Describe the bug ####

Initial setup cannot run all test cases in development
email was missing in generate-auth-header to prevent first time developer to run `createUser`

#### To Reproduce ####

1. Run `yarn generate-auth-header`
2. Create user using the below script
```graphql
mutation createUser {
  createUser {
    email
    name
  }
}
```
3. Error returns
```graphql
{
  "data": {
    "createUser": null
  },
  "errors": [
    {
      "message": "This library (validator.js) validates strings only",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ]
    }
  ]
}
```

#### Expected behavior ####

By using `generate-auth-header`, developer should be able to createUser
Suggestion, add an email placeholder in https://github.com/freeCodeCamp/open-api/blob/40de4e31d1121dfa70519e91a495ccefc0613582/scripts/generateHeader.js#L6

**Comment by user512** [comment]
I am not quite sure if the current setup is intentional but I know added email in `generateHeader` will resolve this problem for me, happy to submit a PR if the above direction is correct.

**Comment by ojongerius** [comment]
Hi @user512 yup! Would be great if you could raise a PR for that.

Ideal would be:

* Patch `scrips/generateHeader.js` to add the email field
* ~~Improve email validation in `createUser`~~
* Test what happens without the email field set. You could set up an extra token in  `test/utils/test-environment.js` and integration test in `test/integration/userFlow.test.js`

**Comment by user512** [comment]
👍 will open a PR today to patch `genereteHeader` and add test.

**Comment by ojongerius** [comment]
Great, thank you!

**Comment by user512** [comment]
#154 patched `genereteHeader.js` and added test in `userFlow.test.js`
