### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/open-api#20]
We should have a docker setup for this early on.

**Comment by ojongerius** [comment]
Keeping this open while we discuss https://github.com/freeCodeCamp/freeCodeCamp/issues/16936, I'd still like to consider using docker images to lock in the mongo version.

Also https://github.com/freeCodeCamp/freeCodeCamp/pull/16937 needs to go in to be able to use it's network.

**Comment by ojongerius** [comment]
Update https://github.com/freeCodeCamp/freeCodeCamp/pull/16937 is blocked on beta.

**Comment by ojongerius** [comment]
Main work went in, just https://github.com/freeCodeCamp/freeCodeCamp/pull/17010 to go.

**Comment by ojongerius** [comment]
Case closed.
