### ISSUE TITLE
As a freeCodeCamp user, I want to programatically retrieve my current challenge

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#22]
As an authenticated codeCamp user, I would to programatically retrieve the current challenge.

**Comment by ojongerius** [comment]
@raisedadead how about this user story as part of spiking GraphQL? What label would you use? I don't see a feature or user story labels in the freeCodeCamp repo. Also, do you, and if so, how do you handle epics?

**Comment by ojongerius** [comment]
@raisedadead I've hacked something together that works, but it's handcrafted instead of generated, and we need to make some decisions about the architecture. I've raised #27 for this.

**Comment by raisedadead** [comment]
I am super psyched to see what you have in mind.

**Comment by raisedadead** [comment]
What label would you use? I don't see a feature or user story labels ...

Lets discuss in the meet.

>  Also, do you, and if so, how do you handle epics?

Would like to use ZenHub https://www.zenhub.com/ ?

**Comment by ojongerius** [comment]
> Would like to use ZenHub https://www.zenhub.com/ ?

I've seen that produc in a demo once, is it something freeCodeCamp has used before?

**Comment by raisedadead** [comment]
Well I use it some times. We can sure use it here, we have used it collectively on freeCodeCamp/wiki in past.

**Comment by ojongerius** [comment]
Ok, sounds good. How do we get started?

**Comment by raisedadead** [comment]
Oh just visit this https://www.zenhub.com/extension and signup. You should start seeing a tab, on GitHub itself.

Then we can create issues as usual and add them to epics etc. (downside, it will only be visible to people using this extension, which is fine if we can add it in docs)

**Comment by ojongerius** [comment]
After an Events team meeting we decided to work on other, event related, user stories first. I'm going to close this off for now.
