### ISSUE TITLE
Decide on authentication

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#23]
* for interactions from a user perspective. This could be the freeCodeCamp website or, for example, software like a IDE plugin that would pull current challenges in, and submit solutions on their behalf 
* for 3rd parties that want to build other functionality -an example being leaderboards

Related issue suggesting to : https://github.com/freeCodeCamp/freeCodeCamp/issues/16104 (limited to Collaborators, so I am unable to chip in 😞 )

I think we should consider using auth0, they provide a secure and scalable solution, and they have a unlimited free tier for open source projects. I doubt we could do a better job than auth0, and it would unblock the team to work on projects.

The library support looks great, see https://auth0.com/opensource They support social providers, passwordless, and MFA, see https://auth0.com/docs/identityprovider for an overview.

/cc @raisedadead @QuincyLarson @BerkeleyTrue

**Comment by ojongerius** [comment]
Related issue https://github.com/freeCodeCamp/freeCodeCamp/issues/15914

**Comment by QuincyLarson** [comment]
@ojongerius I've reached out to Auth0 to request unlimited free access to their service. I agree that we don't want to roll our own authentication. I'll let you know as soon as we hear back.

**Comment by ojongerius** [comment]
@QuincyLarson awesome, looking forward to the update.

**Comment by QuincyLarson** [comment]
@ojongerius Now that we've decided on Auth0 as a solution and have unlimited use of it, I'm closing this issue.
