### ISSUE TITLE
Architecture / data sources

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#27]
Hi there,

We need to make some decisions on how to move forward on this project, and what the scope is going to be. There are a few options to discuss, they should probably be broken apart and judged by their merits, but let's see what options there are first:

We expose GraphQL via this project and operations are resolved..

* using REST calls served by loopback in the freecodecamp site.
* using REST calls served by loopback in this project, models are kept in sync by pushing them into a shared library. Data lives in the current MongoDB server and is read from and written to from both this project and the freecodecamp website.
* using code generated from loopback models that are kept in sync by pushing them into a shared library. Data lives in the current MongoDb server and is read from and written to from both this project and the freecodecamp website.
* we recreate all models by hand in open-api. Just kidding.
* ... your solution here.

One party pooper is that I've seen is that the REST API return responses that I did not expect. An example is hitting http://127.0.0.1:3001/api/users, I happily received a 200 OK, but useless HTML. I've not explored why this is set up like it is, could someone give me some context?

**Comment by ojongerius** [comment]
@raisedadead thoughts? Who would be candidates to chime in? @BerkeleyTrue, @QuincyLarson?

**Comment by raisedadead** [comment]
@ojongerius the idea is to make open-api our primary and sole back-end. So yes this means we will have to recreate the model schema here once again.

I know that's a chore, but in favor of simplicity lets do it. For starters lets make the very first few commits based off of the schema that we have on the main repo.

It is going to be evident that we have to do a hybrid approach for GraphQL and REST,  to keep supporting the client side code in the short term.

**I propose we just use https://www.apollographql.com**

I have seen excellent feedback for them.

We should just ignore, anything Loopback, we aren't going to be using any of its feature. The explorer plugin is not upgraded by us I think, so its not going to work as you have already found.

**Comment by QuincyLarson** [comment]
@ojongerius I just spoke with @raisedadead and @Bouncey and we are in agreement - all data should be exposed through GraphQL.

Our intention is to quickly rip out Loopback and replace it with GraphQL ASAP. 

Don't worry about any sort of backward compatibility - we can overhaul all our other tools to work with GraphQL.

**Comment by ojongerius** [comment]
Great! Thanks for the feedback @raisedadead, @QuincyLarson.

There definitely is less overhead in building a server with GraphQL without implementing REST, so I'm all for it. However, the sceptic person in me says that there might be a real possibility that we will have this reality where we'll have to support both while freeCodeCamp gets an overhaul. 

Ok, so we *are* going to convert all models, but can enjoy support from the team in preventing drift between the 2 models while we are cutting over, is that right @QuincyLarson?

**Comment by QuincyLarson** [comment]
@ojongerius Yes - we're planning to use GraphQL for all freeCodeCamp services (except for the forum, which is sort of it's own monolithic app).

I'm closing this issue since we've decided this aspect of our architecture - feel free to open subsequent issues to discuss other considerations.
