### ISSUE TITLE
Explore testing with Jest

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#32]
As recommended in https://github.com/withspectrum/spectrum/blob/alpha/docs/backend/api/testing.md 

See https://github.com/facebook/jest 

@QuincyLarson @raisedadead @Bouncey any options on testing here, lessons learned that I could build upon?

**Comment by ojongerius** [comment]
I'll actually work on this now instead of later, so we can enjoy that comfortable warm feeling of knowing we did not break things in a too terrible way as early as we can.

**Comment by Bouncey** [comment]
I like tests, I like Jest. 

I like testing with Jest.

Something had me thinking that Leveluptuts had a series on testing graphql, but I can't seem to find it

**Comment by ojongerius** [comment]
My fist impression of Jest is really great, I'll try and get a PR open after the weekend. Have found a few sane looking examples of people using it to test their GraphQL servers, which will help us get started.

**Comment by ojongerius** [comment]
I think I have something that I can turn into a PR tomorrow. It's  just a very simple user test, but with magic sauce (not mine) that spins up a mongodb server in memory.

**Comment by ojongerius** [comment]
Addressed in https://github.com/freeCodeCamp/open-api/pull/69
