### ISSUE TITLE
Deploy toy GraphQL server using Lambda

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#35]
Deploy a simple Lambda serving GraphQL, using Travis. Initially against a small staging database.

- [x] Deploy a Lambda from Travis to AWS
- [x] Deploy a small staging database, mLab was suggested

**Comment by ojongerius** [comment]
Spent some time today on this: I've successfully deployed my lambda (2 endpoints: /api and /graphql) to AWS, under a private account, using the serverless framework, and hooked it up to a free mlab Mongo instance.

To keep things simple I did not use a VPC setup, and used liberal AWS permissions -hence the private account. Just to see all part working.

No auth yet either -thats tracked in https://github.com/freeCodeCamp/open-api/issues/37, and the only thing in the DB is a test account set up using the freecodecamp site running on my machine.

Hooking it up to Travis is trivial -you run the same commands, you just need to configure secret variables, and make decisions about under what conditions we deploy what.

I'm currently doing a little clean up, and will raise a PR with that work in the coming days, depending on how I go -fighting an annoying flue at the moment.

/cc @raisedadead @jrogatis @QuincyLarson @Bouncey

**Comment by QuincyLarson** [comment]
@ojongerius Thanks for the update. It sounds like you're making steady progress. We're all looking forward to taking a look at your PR. Hope you feel better soon!

**Comment by ojongerius** [comment]
Thanks @QuincyLarson! I've raised https://github.com/freeCodeCamp/open-api/pull/42

You can have a look at what I deployed at https://ys2mlj49y9.execute-api.us-east-1.amazonaws.com/dev/api the IDE allows you to explore the schema, and query at will. This is a shared playground to see what queries are possible. Nothing interesting at the moment but it does give you a rough idea: https://graphqlbin.com/v2/2RrgS8

If I can get the PR merged I'll set Travis up, I will probably need some permissions to do so.

**Comment by ojongerius** [comment]
I've merged that PR, and raised another one to update the documentation; #43

**Comment by ojongerius** [comment]
Have raised a PR that will allow Travis deployments https://github.com/freeCodeCamp/open-api/pull/44.

**Comment by ojongerius** [comment]
@jrogatis (or others) if you'd like access to the Mongo db, shoot me a message on Signal and I'll share the Mongo URL. Quincy, Mrugesh and Stuart all have my number.

**Comment by ojongerius** [comment]
I'm going to close this one off, some PRs are still open but the main goal of this issue has been reached.
