### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#37]
We have decided on authentication in #23. We'll now need to think about authorisation.

Authentication can be done using Auth0. Both /graphql and the graphcool IDE endpoints should be approachable without authentication, and only queries and mutations needing authentication should require it.

## User groups ##

* unauthenticated users -this might not be available for a while or at all
* 3rd parties acting on behalf of users
* 3rd parties authenticating with API keys
* logged in users, most likely via the site

## Authorisation ##

There are plenty of options here as the specification does not dictates a solution.

* Business logic layer: the recommendation of the GraphQL best practices doco (http://graphql.org/learn/authorization/)
* Chaining resolvers, see https://github.com/thebigredgeek/apollo-resolvers and the corresponding talk at Apollo Day https://www.youtube.com/watch?v=xaorvBjCE7A
* GraphQL shield is a project separating permission logic from the application logic allowing you to pass your resolvers and a permission object into it's API https://github.com/maticzav/graphql-shield
* Directives, see https://blog.graph.cool/graphql-directive-permissions-authorization-made-easy-54c076b5368e based on a talk by Ryan Chenkie at GraphQL summit: https://www.youtube.com/watch?v=4_Bcw7BULC8
#25 

A related thread full of interesting viewpoints https://github.com/apollographql/graphql-tools/issues/313

**Comment by ojongerius** [comment]
Still working through the pro and cons of some of the solutions on offer. 

Which solution offers the fit best for us is influenced by our approach to schema creation. Part of finding the right fit is figuring out if we want to generate code given a GraphQL schema, or generate GraphQL given a Mongoose schema.

**Comment by Bouncey** [comment]
I like the idea of directives. It looks very clean
