### ISSUE TITLE
Snyk report

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#52]
Thanks for opening up access to Snyk @raisedadead!

There is one low severity vulnerability found; Prototype pollution via the "hoek" module. ( https://snyk.io/vuln/npm:hoek:20180212 )

There are bunch of libraries using it, I've raised a PR for one, but there are a few others and chasing that all up does not seem like a wise use of my time.

Does Snyk support whitelisting of "blessed" vulnerabilities, or do you adjust the sev level and ignore say "low"? @freeCodeCamp/open-api how do you normally handle these reports in the freeCodeCamp org? 

General report: https://snyk.io/test/github/freecodecamp/open-api?severity=high&severity=medium&severity=low

**Comment by Bouncey** [comment]
The [docs](https://snyk.io/docs/ignoring-issues) talk through how to ignore certain issues. I would recommend a temparay ignore for issues without a fix

**Comment by ojongerius** [comment]
👍 just wanted to run it pass you folks.
