### ISSUE TITLE
Relax rules for commit messages

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/open-api#54]
I like the rules for commit messages, but please can we relax them.

My proposal:

`$1($2): $3`

`$1`: One of `feat fix chore docs tests`
`$2`: Any single word, any case
`$3`: Any string, any case

Example:

`feat(types): Expand User type and apply 'on-the-fly' migrations`

Reasoning:

I like to keep my commit messages consistent with the code is touches. If I fix a bug in `someBuggyFunction`, I want to reference it in my commit message. Or if I am working with types, I want to use StartCase in the commit message to reference the type I have worked on, which uses StartCase in the code base.

**Comment by ojongerius** [comment]
I'm all for this.

I do see merit in having consistency in regards to a full stop, the only thing I care about is consistency. Happy to keep enforcing full stops?

**Comment by Bouncey** [comment]
Are we enforcing full stops? Haven't tripped that rule yet

**Comment by ojongerius** [comment]
I'm guilty of having tripped that plenty of times, an old habit. Appears commitlint/config-conventional, which we extend, enforces [subject-full-stop]( https://www.npmjs.com/package/@commitlint/config-conventional#subject-full-stop).

**Comment by Bouncey** [comment]
So, are we saying 

- full stop - yes
or
- full stop - no

??

**Comment by ojongerius** [comment]
Let's keep the default of "full stop - no".

**Comment by user512** [comment]
May I work on this? My assumption to config the `subject-case` rule. (http://marionebl.github.io/commitlint/#/reference-rules?id=subject-case)

**Comment by ojongerius** [comment]
All yours @user512 !

**Comment by user512** [comment]
@Bouncey I tested the PR with your example commit message and returns no error/ warning.
