### ISSUE TITLE
Switch to Yarn broke deployments

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#70]
Failing build: https://travis-ci.org/freeCodeCamp/open-api/builds/370905160
Commit: https://github.com/freeCodeCamp/open-api/commit/06d028e1f76dcfa6fb05f1b3a5971b962c0e50ab

@Bouncey / @raisedadead I'm happy to look at this tomorrow if you don't get around to fixing it.

**Comment by Bouncey** [comment]
I have deleted all caches in case that was an issue and restarted the build on staging. 

Still failing
