### ISSUE TITLE
Current status of the availability of an API key? 

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/open-api#9]
Hi @roelver how are you?

The current readme of the project has a paragraph that shows as follows:

> Getting an API key
> 
> All requests must have a API-key in the request. In this stage there is no online resource to generate an API-key. If you want an API key for your app, please ask for it on the FreeCodeCamp/DataScience Gitter. The API-key is specified in the query string as key=<value>.

This is driving traffic into the room when we haven't been able to give a clear answer about the existence of the API.

Shouldn't that message be changed into something like "on-hold" if the API key is not currently available?

Or should we provide those keys?

**Comment by ojongerius** [comment]
This is related to the old API, the new API is a work in progress. Closing this as stale.
