### ISSUE TITLE
Lambda warming

### ISSUE THREAD

**Issue by ojongerius** [FreeCodeCamp/open-api#97]
A "cold" Lambda takes a while to start. A common technique is to to have a scheduled events invoke the Lambda. This will make AWS start a container and process, which it will then keep around in case another invocation will follow. Those subsequent invocations will be much faster, as all set up has already been done.

Keeping Lambdas warm in a low traffic is important to keep things responsive. However it is not needed if there is enough traffic to have warmed containers around at any time.

Before we spend more time investigating the best way to keep Lambdas warm, could someone provide insights on the frequency and volume of traffic we have, to see if we need to worry about this at all?

@raisedadead, @Bouncey could you shed some light on this?

2 approaches the first approach would be more cost efficient as the warming invocation could have a shorter running time, and hence cost, than an health endpoint invocation. The other plus is that there is no API gateway hit involved either, saving more cost:

* A serverless plugin that creates a scheduled Lambda that can invoke other Lambdas: https://github.com/FidelLimited/serverless-plugin-warmup . A blog post about this plugin: https://serverless.com/blog/keep-your-lambdas-warm . This is kind of approach is referred to in an  AWS answer in  https://forums.aws.amazon.com/thread.jspa?threadID=234124 
* Have a monitoring endpoint hit an health endpoint (like `/health`) to monitor statistics. This invocation would keep the endpoint warm, although there would be a bigger chance of a normal client request then trigger a cold start while the monitoring endpoint is hitting the health endpoint.

**Comment by raisedadead** [comment]
![image](https://user-images.githubusercontent.com/1884376/39550957-c88f91c6-4e80-11e8-9ec2-f8cbdf9e4df4.png)

**Comment by ojongerius** [comment]
With that traffic I don't expect us to need any warming.
